<?php

namespace Database\Seeders;

use App\Models\SocialMediaTemplate;
use Illuminate\Database\Seeder;

class SocialMediaTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // Social Media
            [
                'name' => 'Instagram',
                'slug' => 'instagram',
                'icon' => '📸',
                'url_pattern' => 'https://instagram.com/{username}',
                'category' => 'social_media',
                'color' => '#E4405F',
                'cta_type' => 'external_link',
                'sort_order' => 1,
            ],
            [
                'name' => 'TikTok',
                'slug' => 'tiktok',
                'icon' => '🎵',
                'url_pattern' => 'https://tiktok.com/@{username}',
                'category' => 'social_media',
                'color' => '#000000',
                'cta_type' => 'external_link',
                'sort_order' => 2,
            ],
            [
                'name' => 'YouTube',
                'slug' => 'youtube',
                'icon' => '▶️',
                'url_pattern' => 'https://youtube.com/@{username}',
                'category' => 'social_media',
                'color' => '#FF0000',
                'cta_type' => 'external_link',
                'sort_order' => 3,
            ],
            [
                'name' => 'Facebook',
                'slug' => 'facebook',
                'icon' => '👤',
                'url_pattern' => 'https://facebook.com/{username}',
                'category' => 'social_media',
                'color' => '#1877F2',
                'cta_type' => 'external_link',
                'sort_order' => 4,
            ],
            [
                'name' => 'Twitter / X',
                'slug' => 'twitter',
                'icon' => '🐦',
                'url_pattern' => 'https://x.com/{username}',
                'category' => 'social_media',
                'color' => '#000000',
                'cta_type' => 'external_link',
                'sort_order' => 5,
            ],
            [
                'name' => 'LinkedIn',
                'slug' => 'linkedin',
                'icon' => '💼',
                'url_pattern' => 'https://linkedin.com/in/{username}',
                'category' => 'social_media',
                'color' => '#0A66C2',
                'cta_type' => 'external_link',
                'sort_order' => 6,
            ],
            [
                'name' => 'Threads',
                'slug' => 'threads',
                'icon' => '🧵',
                'url_pattern' => 'https://threads.net/@{username}',
                'category' => 'social_media',
                'color' => '#000000',
                'cta_type' => 'external_link',
                'sort_order' => 7,
            ],
            [
                'name' => 'Telegram',
                'slug' => 'telegram',
                'icon' => '✈️',
                'url_pattern' => 'https://t.me/{username}',
                'category' => 'social_media',
                'color' => '#26A5E4',
                'cta_type' => 'external_link',
                'sort_order' => 8,
            ],
            [
                'name' => 'Discord',
                'slug' => 'discord',
                'icon' => '🎮',
                'url_pattern' => 'https://discord.gg/{username}',
                'category' => 'social_media',
                'color' => '#5865F2',
                'cta_type' => 'external_link',
                'sort_order' => 9,
            ],
            [
                'name' => 'Snapchat',
                'slug' => 'snapchat',
                'icon' => '👻',
                'url_pattern' => 'https://snapchat.com/add/{username}',
                'category' => 'social_media',
                'color' => '#FFFC00',
                'cta_type' => 'external_link',
                'sort_order' => 10,
            ],
            [
                'name' => 'Pinterest',
                'slug' => 'pinterest',
                'icon' => '📌',
                'url_pattern' => 'https://pinterest.com/{username}',
                'category' => 'social_media',
                'color' => '#E60023',
                'cta_type' => 'external_link',
                'sort_order' => 11,
            ],
            [
                'name' => 'Spotify',
                'slug' => 'spotify',
                'icon' => '🎧',
                'url_pattern' => 'https://open.spotify.com/artist/{username}',
                'category' => 'entertainment',
                'color' => '#1DB954',
                'cta_type' => 'external_link',
                'sort_order' => 12,
            ],
            [
                'name' => 'SoundCloud',
                'slug' => 'soundcloud',
                'icon' => '☁️',
                'url_pattern' => 'https://soundcloud.com/{username}',
                'category' => 'entertainment',
                'color' => '#FF5500',
                'cta_type' => 'external_link',
                'sort_order' => 13,
            ],
            [
                'name' => 'Shopee',
                'slug' => 'shopee',
                'icon' => '🛒',
                'url_pattern' => 'https://shopee.co.id/{username}',
                'category' => 'marketplace',
                'color' => '#EE4D2D',
                'cta_type' => 'external_link',
                'sort_order' => 14,
            ],
            [
                'name' => 'Tokopedia',
                'slug' => 'tokopedia',
                'icon' => '🏪',
                'url_pattern' => 'https://tokopedia.com/{username}',
                'category' => 'marketplace',
                'color' => '#03AC0E',
                'cta_type' => 'external_link',
                'sort_order' => 15,
            ],
            [
                'name' => 'Bukalapak',
                'slug' => 'bukalapak',
                'icon' => '📦',
                'url_pattern' => 'https://bukalapak.com/u/{username}',
                'category' => 'marketplace',
                'color' => '#FF5000',
                'cta_type' => 'external_link',
                'sort_order' => 16,
            ],
            [
                'name' => 'Lazada',
                'slug' => 'lazada',
                'icon' => '🏬',
                'url_pattern' => 'https://lazada.co.id/shop/{username}',
                'category' => 'marketplace',
                'color' => '#0F1472',
                'cta_type' => 'external_link',
                'sort_order' => 17,
            ],
            [
                'name' => 'Blibli',
                'slug' => 'blibli',
                'icon' => '📮',
                'url_pattern' => 'https://blibli.com/merchant/{username}',
                'category' => 'marketplace',
                'color' => '#1D45A6',
                'cta_type' => 'external_link',
                'sort_order' => 18,
            ],
            [
                'name' => 'JD.ID',
                'slug' => 'jdid',
                'icon' => '🛍️',
                'url_pattern' => 'https://jd.id/{username}',
                'category' => 'marketplace',
                'color' => '#E2232A',
                'cta_type' => 'external_link',
                'sort_order' => 19,
            ],
            [
                'name' => 'Tiktok Shop',
                'slug' => 'tiktok-shop',
                'icon' => '🛍️',
                'url_pattern' => 'https://shop.tiktok.com/{username}',
                'category' => 'marketplace',
                'color' => '#000000',
                'cta_type' => 'external_link',
                'sort_order' => 20,
            ],
            [
                'name' => 'WhatsApp Personal',
                'slug' => 'whatsapp-personal',
                'icon' => '💬',
                'base_url' => null,
                'category' => 'communication',
                'color' => '#25D366',
                'cta_type' => 'whatsapp',
                'sort_order' => 21,
            ],
            [
                'name' => 'WhatsApp Business',
                'slug' => 'whatsapp-business',
                'icon' => '📱',
                'base_url' => null,
                'category' => 'communication',
                'color' => '#25D366',
                'cta_type' => 'whatsapp',
                'sort_order' => 22,
            ],
            [
                'name' => 'Email',
                'slug' => 'email',
                'icon' => '📧',
                'url_pattern' => 'mailto:{username}',
                'category' => 'communication',
                'color' => '#EA4335',
                'cta_type' => 'external_link',
                'sort_order' => 23,
            ],
            [
                'name' => 'Line',
                'slug' => 'line',
                'icon' => '💬',
                'url_pattern' => 'https://line.me/ti/g/{username}',
                'category' => 'communication',
                'color' => '#00B900',
                'cta_type' => 'external_link',
                'sort_order' => 24,
            ],
            [
                'name' => 'Dana',
                'slug' => 'dana',
                'icon' => '💰',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#118EEA',
                'cta_type' => 'external_link',
                'sort_order' => 25,
            ],
            [
                'name' => 'OVO',
                'slug' => 'ovo',
                'icon' => '💳',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#50005A',
                'cta_type' => 'external_link',
                'sort_order' => 26,
            ],
            [
                'name' => 'GoPay',
                'slug' => 'gopay',
                'icon' => '🚗',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#00A700',
                'cta_type' => 'external_link',
                'sort_order' => 27,
            ],
            [
                'name' => 'ShopeePay',
                'slug' => 'shopeepay',
                'icon' => '📱',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#EE4D2D',
                'cta_type' => 'external_link',
                'sort_order' => 28,
            ],
            [
                'name' => 'BCA',
                'slug' => 'bca',
                'icon' => '🏦',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#00457C',
                'cta_type' => 'external_link',
                'sort_order' => 29,
            ],
            [
                'name' => 'Mandiri',
                'slug' => 'mandiri',
                'icon' => '🏦',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#CC0000',
                'cta_type' => 'external_link',
                'sort_order' => 30,
            ],
            [
                'name' => 'BNI',
                'slug' => 'bni',
                'icon' => '🏦',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#F58022',
                'cta_type' => 'external_link',
                'sort_order' => 31,
            ],
            [
                'name' => 'BRI',
                'slug' => 'bri',
                'icon' => '🏦',
                'base_url' => null,
                'category' => 'payment',
                'color' => '#004226',
                'cta_type' => 'external_link',
                'sort_order' => 32,
            ],
            [
                'name' => 'Linktree',
                'slug' => 'linktree-alternative',
                'icon' => '🔗',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 33,
            ],
            [
                'name' => 'Kitafakta',
                'slug' => 'kitafakta',
                'icon' => '📋',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 34,
            ],
            [
                'name' => 'Portfolio',
                'slug' => 'portfolio',
                'icon' => '💼',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 35,
            ],
            [
                'name' => 'Blog / Website',
                'slug' => 'blog',
                'icon' => '🌐',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 36,
            ],
            [
                'name' => 'Toko Offline',
                'slug' => 'offline-store',
                'icon' => '🏪',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 37,
            ],
            [
                'name' => 'Maps / Lokasi',
                'slug' => 'maps',
                'icon' => '📍',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 38,
            ],
            [
                'name' => 'Custom Link',
                'slug' => 'custom',
                'icon' => '➕',
                'base_url' => null,
                'category' => 'other',
                'color' => '#6366f1',
                'cta_type' => 'external_link',
                'sort_order' => 99,
            ],
        ];

        foreach ($templates as $template) {
            SocialMediaTemplate::updateOrCreate(
                ['slug' => $template['slug']],
                $template
            );
        }
    }
}
