<?php

/**
 * Store Template Presets Configuration
 *
 * Contains all 29 templates (9 original + 20 new)
 * Each template has properties for:
 * - name: display name
 * - background_type: flat/gradient/pattern
 * - bg_color: primary background color (hex)
 * - bg_secondary: secondary color for gradient (hex, nullable)
 * - bg_gradient_direction: gradient direction (to bottom / to top / to right / 135deg etc)
 * - button_color: CTA button color (hex)
 * - text_color: primary text color (hex)
 * - pattern: CSS pattern class if applicable (nullable)
 * - header_gradient_start: header gradient start color
 * - header_gradient_end: header gradient end color
 * - card_bg: card background color
 * - card_text: card text color
 * - special_class: special CSS class for glow effects (nullable)
 */

return [
    // =====================================================
    // ORIGINAL 9 TEMPLATES
    // =====================================================

    'feeling_lucky' => [
        'name' => "I'm Feeling Lucky",
        'background_type' => 'gradient',
        'bg_color' => '#FFFBEB',
        'bg_secondary' => '#FEF3C7',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#F59E0B',
        'text_color' => '#92400E',
        'pattern' => null,
        'header_gradient_start' => '#F59E0B',
        'header_gradient_end' => '#D97706',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'minimal' => [
        'name' => 'Classic',
        'background_type' => 'flat',
        'bg_color' => '#F9FAFB',
        'bg_secondary' => null,
        'bg_gradient_direction' => null,
        'button_color' => '#4F46E5',
        'text_color' => '#1F2937',
        'pattern' => null,
        'header_gradient_start' => '#4F46E5',
        'header_gradient_end' => '#4338CA',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'city_vibes' => [
        'name' => 'City Vibes',
        'background_type' => 'gradient',
        'bg_color' => '#EFF6FF',
        'bg_secondary' => '#DBEAFE',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#1E40AF',
        'text_color' => '#1E3A8A',
        'pattern' => null,
        'header_gradient_start' => '#1E293B',
        'header_gradient_end' => '#334155',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'splash_wave' => [
        'name' => 'Splash Wave',
        'background_type' => 'gradient',
        'bg_color' => '#ECFEFF',
        'bg_secondary' => '#CFFAFE',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#0891B2',
        'text_color' => '#164E63',
        'pattern' => null,
        'header_gradient_start' => '#06B6D4',
        'header_gradient_end' => '#0891B2',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'modern' => [
        'name' => 'Modern',
        'background_type' => 'flat',
        'bg_color' => '#FFFFFF',
        'bg_secondary' => null,
        'bg_gradient_direction' => null,
        'button_color' => '#7C3AED',
        'text_color' => '#1F2937',
        'pattern' => null,
        'header_gradient_start' => '#7C3AED',
        'header_gradient_end' => '#6D28D9',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'bold' => [
        'name' => 'Bold',
        'background_type' => 'gradient',
        'bg_color' => '#ECFDF5',
        'bg_secondary' => '#D1FAE5',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#059669',
        'text_color' => '#065F46',
        'pattern' => null,
        'header_gradient_start' => '#F97316',
        'header_gradient_end' => '#EA580C',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'grinch' => [
        'name' => 'Grinch',
        'background_type' => 'gradient',
        'bg_color' => '#F0FDF4',
        'bg_secondary' => '#DCFCE7',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#10B981',
        'text_color' => '#064E3B',
        'pattern' => null,
        'header_gradient_start' => '#10B981',
        'header_gradient_end' => '#059669',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'funky' => [
        'name' => 'Funky',
        'background_type' => 'gradient',
        'bg_color' => '#FDF2F8',
        'bg_secondary' => '#FCE7F3',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#EC4899',
        'text_color' => '#831843',
        'pattern' => null,
        'header_gradient_start' => '#EC4899',
        'header_gradient_end' => '#DB2777',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    'tropics' => [
        'name' => 'Tropics',
        'background_type' => 'gradient',
        'bg_color' => '#F0FDFA',
        'bg_secondary' => '#CCFBF1',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#14B8A6',
        'text_color' => '#134E4A',
        'pattern' => null,
        'header_gradient_start' => '#14B8A6',
        'header_gradient_end' => '#0D9488',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1F2937',
        'special_class' => null,
    ],

    // =====================================================
    // NEW 20 TEMPLATES
    // =====================================================

    'midnight' => [
        'name' => 'Midnight',
        'background_type' => 'gradient',
        'bg_color' => '#0f0f1a',
        'bg_secondary' => '#1a1a2e',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#7c3aed',
        'text_color' => '#ffffff',
        'pattern' => null,
        'header_gradient_start' => '#7c3aed',
        'header_gradient_end' => '#5b21b6',
        'card_bg' => '#1a1a2e',
        'card_text' => '#e5e7eb',
        'special_class' => null,
    ],

    'rose_gold' => [
        'name' => 'Rose Gold',
        'background_type' => 'gradient',
        'bg_color' => '#f9e4e4',
        'bg_secondary' => '#f4c2c2',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#c0737a',
        'text_color' => '#3d1515',
        'pattern' => null,
        'header_gradient_start' => '#c0737a',
        'header_gradient_end' => '#a8557a',
        'card_bg' => '#FFFFFF',
        'card_text' => '#3d1515',
        'special_class' => null,
    ],

    'ocean_breeze' => [
        'name' => 'Ocean Breeze',
        'background_type' => 'gradient',
        'bg_color' => '#0077b6',
        'bg_secondary' => '#00b4d8',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#ffffff',
        'text_color' => '#ffffff',
        'pattern' => null,
        'header_gradient_start' => '#0077b6',
        'header_gradient_end' => '#00b4d8',
        'card_bg' => '#023e8a',
        'card_text' => '#ffffff',
        'special_class' => null,
    ],

    'matcha' => [
        'name' => 'Matcha',
        'background_type' => 'gradient',
        'bg_color' => '#d8f3dc',
        'bg_secondary' => '#b7e4c7',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#2d6a4f',
        'text_color' => '#1b4332',
        'pattern' => null,
        'header_gradient_start' => '#2d6a4f',
        'header_gradient_end' => '#1b4332',
        'card_bg' => '#FFFFFF',
        'card_text' => '#1b4332',
        'special_class' => null,
    ],

    'sakura' => [
        'name' => 'Sakura',
        'background_type' => 'gradient',
        'bg_color' => '#ffe4e8',
        'bg_secondary' => '#ffc2d4',
        'bg_gradient_direction' => '135deg',
        'button_color' => '#e05780',
        'text_color' => '#3d0018',
        'pattern' => null,
        'header_gradient_start' => '#e05780',
        'header_gradient_end' => '#c9184a',
        'card_bg' => '#FFFFFF',
        'card_text' => '#3d0018',
        'special_class' => null,
    ],

    'sunset_blaze' => [
        'name' => 'Sunset Blaze',
        'background_type' => 'gradient',
        'bg_color' => '#ff6b35',
        'bg_secondary' => '#f7c59f',
        'bg_gradient_direction' => 'to top',
        'button_color' => '#c1440e',
        'text_color' => '#ffffff',
        'pattern' => null,
        'header_gradient_start' => '#ff6b35',
        'header_gradient_end' => '#f7c59f',
        'card_bg' => '#c1440e',
        'card_text' => '#ffffff',
        'special_class' => null,
    ],

    'neon_night' => [
        'name' => 'Neon Night',
        'background_type' => 'flat',
        'bg_color' => '#0d0d0d',
        'bg_secondary' => null,
        'bg_gradient_direction' => null,
        'button_color' => '#39ff14',
        'text_color' => '#39ff14',
        'pattern' => null,
        'header_gradient_start' => '#39ff14',
        'header_gradient_end' => '#32e612',
        'card_bg' => '#1a1a1a',
        'card_text' => '#39ff14',
        'special_class' => 'glow-neon',
    ],

    'cotton_candy' => [
        'name' => 'Cotton Candy',
        'background_type' => 'gradient',
        'bg_color' => '#ffd6e7',
        'bg_secondary' => '#c0e4ff',
        'bg_gradient_direction' => '135deg',
        'button_color' => '#a855f7',
        'text_color' => '#4a0070',
        'pattern' => null,
        'header_gradient_start' => '#a855f7',
        'header_gradient_end' => '#7c3aed',
        'card_bg' => '#FFFFFF',
        'card_text' => '#4a0070',
        'special_class' => null,
    ],

    'dark_chocolate' => [
        'name' => 'Dark Chocolate',
        'background_type' => 'gradient',
        'bg_color' => '#3b1f0a',
        'bg_secondary' => '#5c3317',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#d4a373',
        'text_color' => '#fefae0',
        'pattern' => null,
        'header_gradient_start' => '#5c3317',
        'header_gradient_end' => '#3b1f0a',
        'card_bg' => '#2a1508',
        'card_text' => '#fefae0',
        'special_class' => null,
    ],

    'arctic' => [
        'name' => 'Arctic',
        'background_type' => 'gradient',
        'bg_color' => '#e8f4f8',
        'bg_secondary' => '#daf0fa',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#0096c7',
        'text_color' => '#023e8a',
        'pattern' => null,
        'header_gradient_start' => '#0096c7',
        'header_gradient_end' => '#0077b6',
        'card_bg' => '#FFFFFF',
        'card_text' => '#023e8a',
        'special_class' => null,
    ],

    'lemon_zest' => [
        'name' => 'Lemon Zest',
        'background_type' => 'gradient',
        'bg_color' => '#fffacd',
        'bg_secondary' => '#fff176',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#f59e0b',
        'text_color' => '#78350f',
        'pattern' => null,
        'header_gradient_start' => '#f59e0b',
        'header_gradient_end' => '#d97706',
        'card_bg' => '#FFFFFF',
        'card_text' => '#78350f',
        'special_class' => null,
    ],

    'lavender_dream' => [
        'name' => 'Lavender Dream',
        'background_type' => 'gradient',
        'bg_color' => '#ede7f6',
        'bg_secondary' => '#d1c4e9',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#7e57c2',
        'text_color' => '#311b92',
        'pattern' => null,
        'header_gradient_start' => '#7e57c2',
        'header_gradient_end' => '#5e35b1',
        'card_bg' => '#FFFFFF',
        'card_text' => '#311b92',
        'special_class' => null,
    ],

    'cyberpunk' => [
        'name' => 'Cyberpunk',
        'background_type' => 'flat',
        'bg_color' => '#1a0033',
        'bg_secondary' => null,
        'bg_gradient_direction' => null,
        'button_color' => '#ff007f',
        'text_color' => '#00ffff',
        'pattern' => null,
        'header_gradient_start' => '#ff007f',
        'header_gradient_end' => '#cc0066',
        'card_bg' => '#0d001a',
        'card_text' => '#00ffff',
        'special_class' => 'glow-cyberpunk',
    ],

    'forest_walk' => [
        'name' => 'Forest Walk',
        'background_type' => 'gradient',
        'bg_color' => '#1b4332',
        'bg_secondary' => '#2d6a4f',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#95d5b2',
        'text_color' => '#ffffff',
        'pattern' => null,
        'header_gradient_start' => '#2d6a4f',
        'header_gradient_end' => '#1b4332',
        'card_bg' => '#1b4332',
        'card_text' => '#ffffff',
        'special_class' => null,
    ],

    'peach_cream' => [
        'name' => 'Peach Cream',
        'background_type' => 'gradient',
        'bg_color' => '#fff3e0',
        'bg_secondary' => '#ffe0b2',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#fb8c00',
        'text_color' => '#4e2600',
        'pattern' => null,
        'header_gradient_start' => '#fb8c00',
        'header_gradient_end' => '#e65100',
        'card_bg' => '#FFFFFF',
        'card_text' => '#4e2600',
        'special_class' => null,
    ],

    'slate' => [
        'name' => 'Slate',
        'background_type' => 'gradient',
        'bg_color' => '#334155',
        'bg_secondary' => '#1e293b',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#94a3b8',
        'text_color' => '#f1f5f9',
        'pattern' => null,
        'header_gradient_start' => '#334155',
        'header_gradient_end' => '#1e293b',
        'card_bg' => '#1e293b',
        'card_text' => '#f1f5f9',
        'special_class' => null,
    ],

    'bubblegum' => [
        'name' => 'Bubblegum',
        'background_type' => 'gradient',
        'bg_color' => '#ff70a6',
        'bg_secondary' => '#ff9770',
        'bg_gradient_direction' => '135deg',
        'button_color' => '#ffffff',
        'text_color' => '#5c0028',
        'pattern' => null,
        'header_gradient_start' => '#ff70a6',
        'header_gradient_end' => '#ff9770',
        'card_bg' => '#FFFFFF',
        'card_text' => '#5c0028',
        'special_class' => null,
    ],

    'monochrome' => [
        'name' => 'Monochrome',
        'background_type' => 'flat',
        'bg_color' => '#ffffff',
        'bg_secondary' => null,
        'bg_gradient_direction' => null,
        'button_color' => '#000000',
        'text_color' => '#000000',
        'pattern' => null,
        'header_gradient_start' => '#000000',
        'header_gradient_end' => '#1a1a1a',
        'card_bg' => '#FFFFFF',
        'card_text' => '#000000',
        'special_class' => 'border-monochrome',
    ],

    'aurora' => [
        'name' => 'Aurora',
        'background_type' => 'gradient',
        'bg_color' => '#003366',
        'bg_secondary' => '#7b2d8b',
        'bg_gradient_direction' => '135deg',
        'button_color' => '#ffffff',
        'text_color' => '#ffffff',
        'pattern' => null,
        'header_gradient_start' => '#003366',
        'header_gradient_end' => '#7b2d8b',
        'card_bg' => 'rgba(255,255,255,0.15)',
        'card_text' => '#ffffff',
        'special_class' => null,
    ],

    'caramel_latte' => [
        'name' => 'Caramel Latte',
        'background_type' => 'gradient',
        'bg_color' => '#f5e6d3',
        'bg_secondary' => '#e8c99a',
        'bg_gradient_direction' => 'to bottom',
        'button_color' => '#7c4a1e',
        'text_color' => '#3e1f00',
        'pattern' => null,
        'header_gradient_start' => '#7c4a1e',
        'header_gradient_end' => '#5c3317',
        'card_bg' => '#FFFFFF',
        'card_text' => '#3e1f00',
        'special_class' => null,
    ],
];
